// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSyg-Ut6WE21w98uf199MVy91vRsfWNc',
    appId: '1:50808228839:web:5903021a413a5eec644b42',
    messagingSenderId: '50808228839',
    projectId: 'burakio2025',
    authDomain: 'burakio2025.firebaseapp.com',
    storageBucket: 'burakio2025.firebasestorage.app',
    measurementId: 'G-RQV84HSXHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5UgIohkfxgWVrForrdVjmZLYr2GzO_Tw',
    appId: '1:50808228839:android:60628b5216e6d856644b42',
    messagingSenderId: '50808228839',
    projectId: 'burakio2025',
    storageBucket: 'burakio2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovuCpz8yUhkWokB5KIlFr43elEFof_NI',
    appId: '1:50808228839:ios:50417c8626f80242644b42',
    messagingSenderId: '50808228839',
    projectId: 'burakio2025',
    storageBucket: 'burakio2025.firebasestorage.app',
    iosBundleId: 'com.example.burakio2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBovuCpz8yUhkWokB5KIlFr43elEFof_NI',
    appId: '1:50808228839:ios:50417c8626f80242644b42',
    messagingSenderId: '50808228839',
    projectId: 'burakio2025',
    storageBucket: 'burakio2025.firebasestorage.app',
    iosBundleId: 'com.example.burakio2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSyg-Ut6WE21w98uf199MVy91vRsfWNc',
    appId: '1:50808228839:web:1e9646541bd84436644b42',
    messagingSenderId: '50808228839',
    projectId: 'burakio2025',
    authDomain: 'burakio2025.firebaseapp.com',
    storageBucket: 'burakio2025.firebasestorage.app',
    measurementId: 'G-4B75CPYB54',
  );
}
